### ISSUE TITLE
[P0] Fix coverage-ratchet workflow: greedy sed corrupts .projenrc.ts branches field

### ISSUE THREAD

**Issue by scottschreckengaust** [scottschreckengaust/framework-for-github-app-on-aws#72]
## Problem

The coverage-ratchet workflow (introduced in PR #60) uses sed to update coverage thresholds in `.projenrc.ts`. The sed pattern for `branches` is too greedy — it matches **all** occurrences of `branches:` in the file, not just the one inside `coverageThreshold`.

This corrupts line 358:
```typescript
// BEFORE (correct)
push: { branches: ["main"] }

// AFTER ratchet runs (corrupted)
push: { branches: 80 }
```

The subsequent `npx projen` fails with:
```
TS7053: Element implicitly has an 'any' type because expression of type '"main"' can't be used to index type 'Number'.
Property 'main' does not exist on type 'Number'.
```

## Impact

- **All CI builds on main are failing** (ratchet job)
- The build job also fails because `npx projen build` in sub-packages hits the same TS error

## Root Cause

The ratchet workflow sed command likely does something like:
```bash
sed -i "s/branches: [0-9]*/branches: $NEW_BRANCHES/" .projenrc.ts
```

This matches both:
- `branches: 80,` (coverage threshold — intended)
- `branches: ["main"]` (workflow trigger — unintended)

## Fix

Make the sed pattern more specific — match only within the `coverageThreshold` block, or anchor on surrounding context (e.g., match `branches: <number>,` with trailing comma and indent).

## Acceptance Criteria

- [ ] Ratchet workflow only modifies coverage threshold values
- [ ] `push: { branches: ["main"] }` is never touched
- [ ] CI passes on main after fix
- [ ] Ratchet can still bump thresholds correctly
